//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuestBookZhKassenov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string homepage { get; set; }
        public string text { get; set; }
        public string IP { get; set; }
        public string browser { get; set; }
        public System.DateTime systime { get; set; }
    }
}
